export const TOGGLE_AUTH_STATE = "TOGGLE_AUTH_STATE";
export const SET_USER = "SET_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const GET_HOME_DATA = "GET_HOME_DATA";
export const TOGGLE_HOME_FETCHING_STATE = "TOGGLE_HOME_FETCHING_STATE";